apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-env-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-env-dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: multi-env-dev
    spec:
      containers:
      - name: multi-env-dev
        image: mulevenkatesh/multi-env-pipeline:IMAGE_TAG
        ports:
        - containerPort: 8080
        env:
        - name: BUILD_NUMBER
          value: "IMAGE_TAG"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5